<?php
/**
 * Starter file for the theme default main functionality.
 *
 * @package ambassador-zermatt
 * @subpackage Functionality
 * @since 1.0.0
 */

/**
 * Setup theme
 */
function az_theme_setup() {

	register_nav_menus(
		array(
			'main-menu'                   => __( 'Main Menu', 'ambassador' ),
			'main-mega-menu'              => __( 'Main Mega Menu', 'ambassador' ),
			'footer-copyright-menu'       => __( 'Footer Copyright Menu', 'ambassador' ),
			'footer-hotel-menu'           => __( 'Footer Hotel Menu', 'ambassador' ),
			'footer-gastronomie-menu'     => __( 'Footer Gastronomie Menu', 'ambassador' ),
			'footer-uber-uns-menu'        => __( 'Footer Uber Uns Menu', 'ambassador' ),
			'footer-zermatt-erleben-menu' => __( 'Footer Zermatt Erleben Menu', 'ambassador' ),
		)
	);

	add_theme_support( 'menus' );

	add_theme_support( 'custom-logo' );

	add_theme_support( 'title-tag' );

	add_theme_support( 'post-thumbnails' );

	add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption', 'style', 'script' ) );

	add_post_type_support( 'page', 'excerpt' );

	//add_image_size( 'zimmer-image', 1400, 770, array( 'center', 'center' ) );

}

add_action( 'after_setup_theme', 'az_theme_setup' );

/**
 * Register our sidebars and widgetized areas.
 */
function az_theme_footer_widgets_init() {

	register_sidebar(
		array(
			'name'          => 'Footer',
			'id'            => 'footer',
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widget-title">',
			'after_title'   => '</h3>',
		),
	);

	register_sidebar(
		array(
			'name'          => 'Header Language Switcher',
			'id'            => 'header_ls',
			'before_widget' => '<div id="%1$s" class="%2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '',
			'after_title'   => '',
		)
	);

}

add_action( 'widgets_init', 'az_theme_footer_widgets_init' );


/**
 * Enqueue styles and scripts
 */
function az_theme_enqueue_styles() {

	// Get the theme data.
	$the_theme     = wp_get_theme();
	$theme_version = $the_theme->get( 'Version' );

	// Register Theme main style.
	wp_enqueue_style( 'theme-styles', get_template_directory_uri() . '/dist/css/main.css', array(), $theme_version );

	// https://use.typekit.net/yjm6usa.css first loaded fonts library.
	wp_enqueue_style( 'typekit-fonts', 'https://use.typekit.net/yjm6usa.css', array(), null );

	wp_enqueue_script( 'jquery', false, array(), $theme_version, true );
	wp_enqueue_script( 'theme-scripts', get_stylesheet_directory_uri() . '/dist/js/main.js', array( 'jquery' ), $theme_version, true );

	if ( is_page_template( 'page-templates/page-arrival-contacts.php' ) || is_admin() ) :
		wp_enqueue_script( 'google-map-settings', get_stylesheet_directory_uri() . '/assets/js/google-maps.js', array( 'jquery' ), $theme_version, true );
		wp_enqueue_script( 'google-map-api', 'https://maps.googleapis.com/maps/api/js?key=' . AZ_GOOGLE_MAPS_API_KEY . '&callback=initMap&loading=async', array(), null, true );
	endif;

}

add_action( 'wp_enqueue_scripts', 'az_theme_enqueue_styles' );


/**
 * Load Typekit fonts asynchronously to avoid render-blocking.
 *
 * Intercepts the default <link rel="stylesheet"> tag generated by WordPress
 * for the 'typekit-fonts' handle and replaces it with a non-blocking preload
 * pattern. The preconnect hint is handled separately via az_theme_resource_hints().
 *
 * @param string $html   The full <link> tag HTML generated by WordPress.
 * @param string $handle The registered style handle.
 * @return string
 */
function az_typekit_non_blocking_loader( string $html, string $handle ): string {
	if ( 'typekit-fonts' !== $handle ) {
		return $html;
	}

	return '<link rel="preload" href="https://use.typekit.net/yjm6usa.css" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">' . "\n"
		. '<noscript><link rel="stylesheet" href="https://use.typekit.net/yjm6usa.css"></noscript>' . "\n";
}
add_filter( 'style_loader_tag', 'az_typekit_non_blocking_loader', 10, 2 );

/**
 * Add preconnect and DNS-prefetch resource hints for external origins.
 *
 * Uses the WordPress resource hints API (wp_resource_hints) to register
 * early connection hints for third-party domains used by the theme.
 *
 * @param array  $hints         URLs to print for resource hints.
 * @param string $relation_type The relation type (preconnect, dns-prefetch, etc.).
 * @return array
 */
function az_theme_resource_hints( array $hints, string $relation_type ): array {
	if ( 'preconnect' === $relation_type ) {
		$hints[] = array(
			'href'        => 'https://use.typekit.net',
			'crossorigin' => 'anonymous',
		);
		$hints[] = array(
			'href' => 'https://maps.googleapis.com',
		);
	}

	if ( 'dns-prefetch' === $relation_type ) {
		$hints[] = array( 'href' => 'https://www.google-analytics.com' );
	}

	return $hints;
}
add_filter( 'wp_resource_hints', 'az_theme_resource_hints', 10, 2 );

/**
 * Initialize Google Map API key for ACF in admin.
 */
function ambassador_google_map_init() {
	if ( is_admin() ) :
		acf_update_setting( 'google_api_key', AZ_GOOGLE_MAPS_API_KEY );
	endif;
}
add_action( 'acf/init', 'ambassador_google_map_init' );

/**
 * Remove <p> Tag From Contact Form 7.
 */
add_filter( 'wpcf7_autop_or_not', '__return_false' );

/**
 * Lowers the metabox priority to 'core' for Yoast SEO's metabox.
 *
 * @param string $priority The current priority.
 *
 * @return string $priority The potentially altered priority.
 */
function az_theme_lower_yoast_metabox_priority( $priority ) {
	return 'core';
}

add_filter( 'wpseo_metabox_prio', 'az_theme_lower_yoast_metabox_priority' );

/**
 * Add dynamic favicons for light/dark mode.
 */
function ambz_dynamic_favicons() {
	?>
	<!-- Dynamic favicons based on prefers-color-scheme -->
	<link rel="icon" href="<?php echo esc_url( get_theme_file_uri( 'assets/img/favicon/favicon-dark.png' ) ); ?>" media="(prefers-color-scheme: light)">
	<link rel="icon" href="<?php echo esc_url( get_theme_file_uri( 'assets/img/favicon/favicon-light.png' ) ); ?>" media="(prefers-color-scheme: dark)">
	<?php
}
add_action( 'wp_head', 'ambz_dynamic_favicons' );

// Theme custom template tags.
require get_template_directory() . '/inc/theme-template-tags.php';

// The theme admin settings.
require get_template_directory() . '/inc/theme-admin-settings.php';

// The theme custom menu walker settings.
require get_template_directory() . '/inc/theme-custom-menu-walker.php';


// Debug function to log data to the browser console.
require get_template_directory() . '/inc/theme-optimizations.php';

/**
 * Logs data to the browser console for debugging purposes.
 *
 * @param mixed ...$data The data to log to the console.
 */
function my_console_log( ...$data ) {
	$json = wp_json_encode( $data );
	add_action(
		'shutdown',
		function () use ( $json ) {
			echo "<script>console.log({$json})</script>";
		}
	);
}
